# Generated by Django 4.0.4 on 2022-04-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mango',
            name='username',
            field=models.CharField(max_length=32, verbose_name='사용자명'),
        ),
    ]
