# Generated by Django 4.0.4 on 2022-04-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0002_alter_mango_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mango',
            options={'verbose_name': '유월드 사용자', 'verbose_name_plural': '유월드 사용자'},
        ),
    ]
