# Generated by Django 4.0.4 on 2022-04-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0003_alter_mango_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mango',
            name='useremail',
            field=models.EmailField(default='test@gmaik.com', max_length=128, verbose_name='사용자 이메일'),
            preserve_default=False,
        ),
    ]
